### ISSUE TITLE
feat(docs): Key advantages

### ISSUE THREAD

**Issue by rbalet** [CodeAndWeb/ngx-translate#1]
Hi, I couldn't find where to edit the doc, can you point it out?

About the `Key Advantages`. 

I would propose to do more of a `Pros` and `Cons` on the why we should or shouldn't use this library.

My point is, the `Smaller Deployment Size` this is kinda not true. 
Let say you would have use the angular internationalization library, then you would have had even smaller Deployment size.  which makes your app way faster to load. (So this would be a con actually of this library).

A plus would be that, if you cannot use internationalization, then this is the way to go. (Using Ionic being a example of a reason).

What do you think? (It could help people)

**Comment by CodeAndWeb** [comment]
I've put the doc sources online: https://github.com/CodeAndWeb/ngx-translate.org
Yes... I use react ;-)

I've also adjusted that section.
