### ISSUE TITLE
fix doc

### ISSUE THREAD

**Issue by mzeromski** [CodeAndWeb/ngx-translate#2]
Hi

On this page, just fix code

https://ngx-translate.org/getting-started/installation/

from 
```
  provideTranslateService({
     defaultLanguage: 'en'
    ])
```

to 
```  provideTranslateService({
     defaultLanguage: 'en'
    })
```

] -> }

thanks!

**Comment by CodeAndWeb** [comment]
Fixed. Thanks for reporting this issue!
